feat: Size operator
lenra-io/query-parser pull request #35
Opened 2023-05-04 07:52 UTC by jonas-martinez

Closes #29 

## Description of the changes

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [x] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

## Technical highlight/advice

2023-05-15 07:51 UTC, jonas-martinez commented
@pichoemr Can you resolve the conflicts ?

2023-05-15 12:56 UTC, taorepoara commented on test/exec_test.exs
> +      assert_raise ArgumentError, fn -> parse_and_exec(data(), %{"_id" => %{"$size" => 5}}) end
I've tested the $size operator on other fields than array and the data is just filtered just like if it returs 0.

2023-05-23 08:13 UTC, pichoemr requested changes

2023-05-23 08:13 UTC, pichoemr commented on lib/exec.ex
> +        elem_value |> length() == exec_value(value, elem, ctx)
```suggestion
      "$size" ->
        if is_list(elem_value) do
            elem_value |> length() == exec_value(value, elem, ctx)
        else
            false
        end
```

2023-05-30 08:27 UTC, taorepoara approved these changes

2023-05-30 10:12 UTC, taorepoara approved these changes

2023-05-30 11:57 UTC, pichoemr requested changes

2023-05-30 11:57 UTC, pichoemr commented on lib/exec.ex
> +    exec_value_operator?(operator, value, elem_value, elem, ctx)
```suggestion
    exec_value_operator?(operator, elem_value, exec_value(value, elem, ctx))
```

2023-05-30 11:57 UTC, pichoemr commented on lib/exec.ex
> +  end
```suggestion
  defp exec_value_operator?("$eq",  elem_value, value) do
    elem_value == value  end
```
Same on other exec_value_operator?

2023-05-30 11:57 UTC, pichoemr commented on lib/exec.ex
> +  end
```suggestion
  defp exec_value_operator?("$size", value, elem_value, elem, ctx) when is_list(elem_value) do
      elem_value |> length() == exec_value(value, elem, ctx)
end
  
defp exec_value_operator?("$size", value, elem_value, elem, ctx) do
      false
end
```
Pattern matching is more efficient than if, it's a minor optimization but in this case, it doesn't cost much to do it.

2023-05-30 13:16 UTC, pichoemr approved these changes

2023-05-30 13:18 UTC, merged

2023-05-30 13:19 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.23 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/query-parser/releases/tag/v1.0.0-beta.23)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: